env_file = '.env'

[settings]
experimental = true
legacy_version_file = false  # Don't auto-detect from .python-version files

[tools]
uv = "latest"

[env]
_.python.venv = ".venv"


[tasks.ccusage]
run = [
	"bunx ccusage blocks --live"
]

[tasks.format-github-refs]
description = "Format unformatted GitHub references in markdown files"
run = [
	"./mise-tasks/format-github-refs"
]

[tasks.lint]
description = "Run linting checks on the codebase"
run = [
	"uv run ruff check packages/journal-lib/src/",
	"echo '✅ Ruff linting passed'"
]

[tasks.format]
description = "Format code with ruff"
run = [
	"uv run ruff format packages/journal-lib/src/",
	"echo '✅ Code formatted with ruff'"
]

[tasks.typecheck]
description = "Run type checking with ty (Astral's fast type checker)"
run = [
	"uv run ty check packages/journal-lib/src/",
	"echo '✅ Type checking passed with ty'"
]

[tasks.test]
description = "Run tests with coverage"
run = [
	"uv run pytest packages/journal-lib/tests/ -v --cov=journal_lib --cov-report=term-missing --cov-fail-under=90",
	"echo '✅ Tests passed with coverage ≥90%'"
]

[tasks.check]
description = "Run all quality checks (lint, format check, typecheck, test)"
run = [
	"mise run lint",
	"uv run ruff format --check packages/journal-lib/src/",
	"mise run typecheck", 
	"mise run test",
	"echo '🎉 All quality checks passed!'"
]
