env_file = '.env'

[settings]
experimental = true
legacy_version_file = false  # Don't auto-detect from .python-version files

[tools]
uv = "latest"

[env]
_.python.venv = ".venv"


[tasks.ccusage]
run = [
	"bunx ccusage blocks --live"
]

[tasks.format-github-refs]
description = "Format unformatted GitHub references in markdown files"
run = [
	"./mise-tasks/format-github-refs"
]
