site_name: Tasks Documentation
site_description: Personal tasks repository documentation
site_author: seletz
site_url: https://seletz.github.io/tasks-docs/
repo_name: seletz/tasks-docs
repo_url: https://github.com/seletz/tasks-docs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Mise Tasks:
    - mise-tasks/index.md
    - Tasks: mise-tasks/tasks.md
  - Python Library:
    - library/index.md
    - API Reference: reference/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [packages/journal-lib/src]
          options:
            docstring_style: sphinx
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seletz