[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "journal-lib"
version = "0.1.0"
description = "Personal journal automation library with GitHub integration"
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/journal_lib"]